### ISSUE TITLE
TL-001 Sign in

### ISSUE THREAD

**Issue by Irma1997** [sw21-tug/Team_14#1]
**Description:**

As an unregistered user, I want to be able to create my account, so that I can store my data.

**Acceptance criteria:**

When the application is first opened, it shows a view, where a user can register, if no account has been created yet.
If the account exists, user should be able to login.

**Comment by MuhDur** [comment]
https://firebase.google.com/docs/database/android/read-and-write#kotlin+ktx

https://developer.android.com/codelabs/advanced-android-kotlin-training-login#3
